Controllers/StudentExamController.cs
using Exam.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Exam.Controllers
{
    public class StudentExamController : Controller
    {
        private readonly ExamContext _context;

        public StudentExamController(ExamContext context)
        {
            _context = context;
        }
        public IActionResult Available()
        {
            int studentId = GetCurrentStudentId();

            
            var courseIds = _context.CourseRegistrations
                .Where(r => r.StudentId == studentId)
                .Select(r => r.CourseAllocation.CourseId)
                .Distinct()
                .ToList();

          
            var exams = _context.Assessments
                .Where(a => courseIds.Contains(a.CourseId)
                    && a.IsActive
                    && !a.IsDeleted
                    && DateTime.Now >= a.StartDate
                    && DateTime.Now <= a.EndDate)
                .Include(a => a.Course)
                .Include(a => a.AssessmentType)
                .ToList();

            return View(exams);
        }


        private int GetCurrentStudentId()
        {
            return _context.Students
                .Where(s => s.User.Email == User.Identity.Name)
                .Select(s => s.Id)
                .FirstOrDefault();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/StudentExam/Available.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Exam.Models.Assessment>
@{
    ViewData["Title"] = "Available Exams";
}

<h2>Available Exams</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Course</th>
            <th>Type</th>
            <th>Start</th>
            <th>End</th>
            <th>Duration</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var exam in Model)
        {
            <tr>
                <td>@exam.Course.Code</td>
                <td>@exam.AssessmentType.Name</td>
                <td>@exam.StartDate.ToString("g")</td>
                <td>@exam.EndDate.ToString("g")</td>
                <td>@exam.DurationMinutes.Minute mins</td>
                <td>
                    <a href="@Url.Action("Start", "StudentExam", new { id = exam.Id })" class="btn btn-success">Start Exam</a>
                </td>
            </tr>
        }
    </tbody>
</table>